name: terrform Duo Cloud deployment pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  duo-cloud-deployment:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    steps:
      - name: pull code
        uses: actions/checkout@v6.0.2
      - name: Azure Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3 
        with:
          terraform_wrapper: false 

      - name: Terraform init
        run: terraform init -input=false

      - name: terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: terraform apply
        run: terraform apply -input=false -auto-approve tfplan

      - name: FinOps Automatic Teardown Recovery
        if: failure()
        run: |
            echo "⚠️ CRITICAL ALERT: A validation checkpoint failed. Initiating automatic out-of-pocket budget protection cleanup..."
            terraform destroy -auto-approve
