name: Cloud DevSecOps Pipeline
on: [push, workflow_dispatch]

jobs:
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          skip_check:
            CKV_AWS_355,CKV_AWS_290,CKV_AWS_338,CKV_AWS_158'
          soft_fail: true
  

      - name: configuration test
        run: |
             docker run --rm -v $(pwd):/project openpolicyagent/conftest test plan.json

  security_scan:
      name: Security Scans (Gitleaks, SAST Scan)
      needs: terraform-scan
      runs-on: ubuntu-latest
      steps:
        - name: Code Checkout
          uses: actions/checkout@v6
          with:
            fetch-depth: 0
  
        - name: Secrets Scan
          run: |
             echo "Downloading latest standalone open-source Gitleaks core..."
             wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
             tar -zxvf gitleaks_8.18.2_linux_x64.tar.gz
             chmod +x gitleaks
             
             ./gitleaks detect --verbose --redact
  
        - name: Code Checkout
          uses: actions/checkout@v6
          
        - name: SAST Scan (Semgrep)
          run: |
            docker run --rm -v "${{ github.workspace }}:/src" semgrep/semgrep \
            semgrep scan --config auto --error

  image_build_scan:
      name: Docker Build and Image Scan
      needs: security_scan
      runs-on: ubuntu-latest
  
      steps:
        - name: Code Checkout
          uses: actions/checkout@v6
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Compile and Push Order Service Container
          run: |
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest .
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest
  
        - name: Trivy Image Scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest
            format: 'table'
            exit-code: '1' 
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            trivyignore: .trivyignore
            skip-files: 'app/certs/server.key'



  dast-security-scan:
      name: "OWASP ZAP Baseline Scan"
      needs: image_build_scan
      runs-on: ubuntu-latest
      timeout-minutes: 20
      steps:
        - name: Create local test network
          run: |
                  docker network create capstone-net
        
        - name: Spin Up Application Run Instance
          run: |
            docker run -d --name capstone-store --network capstone-net   wmiv/capstone
            sleep 5

        - name: Execute OWASP ZAP DAST Baseline Scan
          run: |
                mkdir -p zap-reports
                chmod 777 zap-reports
                
                docker run --rm \
                  --network capstone-net \
                  -v $(pwd)/zap-reports:/zap/wrk/:rw \
                  ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
                  -t https://capstone-store:5670/ \
                  -r dast-security-report.html || true

        - name: Upload ZAP DAST report
          uses: actions/upload-artifact@v4
          if: always()
          with:
                  name: zap-dast-report
                  path: zap-reports/


  software-bill-of-materials:
    name: "SBOM by Syft"
    needs: image_build_scan
    runs-on: ubuntu-latest
    steps: 
      - name: generate software Bill of Materials
        run: |
          mkdir -p sbom-reports

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD/sbom-reports:/sbom" \
            anchore/syft:latest \
            wmiv/capstone:latest \
            -o spdx-json=/sbom/meridian-static-app-sbom.spdx.json

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/syft:latest \
            wmiv/capstone:latest \
            -o table \
            > sbom-reports/meridian-static-app-sbom.txt

      - name: Upload SBOM reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-report
          path: sbom-reports/
